<?php

define('FIREBASE_MESSAGE_STATUS_NEW', 1);
define('FIREBASE_MESSAGE_STATUS_UNREAD', 2);
define('FIREBASE_MESSAGE_STATUS_READ', 3);

// @TODO=========================
//   Get rid of "cloud" in the code, Firebase don't use it, they just use
//   messaging it'll save lots of code too.
// @TODO=========================

require_once('includes/cloud-messaging.inc');

/**
 * Implements hook_ctools_plugin_api().
 */
function firebase_ctools_plugin_api($owner, $api) {
  if ($owner == 'services' && $api == 'services') {
    return array(
      'version' => 3,
      'file' => 'firebase.services.inc'
    );
  }
}

/**
 * Implements hook_permission()
 */
function firebase_permission() {
  return array(
    'administer firebase' => array(
      'title' => t('Administer Firebase'),
      'description' => t('Perform administration tasks for Firebase.'),
    ),
    'create fcm token' => array(
      'title' => t('create Firebase Cloud Messaging token')
    ),
    'retrieve fcm token' => array(
      'title' => t('retrieve own Firebase Cloud Messaging token')
    ),
    'update fcm token' => array(
      'title' => t('update own Firebase Cloud Messaging token')
    ),
    'delete fcm token' => array(
      'title' => t('delete own Firebase Cloud Messaging token')
    ),
  );
}

/**
 * Implements hook_menu().
 */
function firebase_menu() {
  $items = array();
  $items['admin/config/services/firebase'] = array(
    'title' => 'Firebase',
    'description' => 'Configuration - Firebase',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('firebase_config_form'),
    'access arguments' => array('administer firebase'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'forms/form.config.inc'
  );
  $items['admin/config/services/firebase/cloud-messaging/send'] = array(
    'title' => 'Send - Firebase Cloud Messaging',
    'description' => 'Send a message with Firebase Cloud Messaging',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('firebase_cloud_messaging_send_form'),
    'access arguments' => array('administer firebase'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'forms/form.cloud-messaging-send.inc'
  );
  return $items;
}

/**
 * HELPERS
 */

/**
 * Returns a count of messages, grouped by message status for a particular user.
 * If no status is passed in, an array will be returned keyed by the status id
 * and the count as the value. If a status is passed in, that count will be
 * returned. If no user id is passed in, it'll default to the current user.
 * @param null $status
 * @param null $uid
 * @return array
 */
function firebase_message_status_count($status = NULL, $uid = NULL) {
  if (!$uid) { $uid = $GLOBALS['user']->uid; }

  $query = db_select('firebase_cloud_messaging_messages', 'm')
    ->fields('m', array('status'))
    ->condition('m.uid', $uid);

  if ($status) {
    $query->condition('m.status', $status);
  }

  $query->groupBy('m.status');
  $query->addExpression('COUNT(m.mid)', 'msgCount');

  $results = $query->execute();
  if (!$status) {
    $rows = array();
    while ($row = $results->fetchObject()) {
      $rows[$row->status] = $row->msgCount;
    }
    return $rows;
  }
  $row = $results->fetchObject();
  return $row ? $row->msgCount : 0;
}

function firebase_message_status_valid($status) {
  return in_array($status, array(
    FIREBASE_MESSAGE_STATUS_NEW,
    FIREBASE_MESSAGE_STATUS_UNREAD,
    FIREBASE_MESSAGE_STATUS_READ
  ));
}


function firebase_cloud_messaging_ok($watchdog = FALSE) {

  $problems = [];

  // sender id
  if (variable_get('firebase_cloud_messaging_sender_id', '') == '') {
    $problems[] = t('You must set the sender id to send a message.');
  }

  // project id
  if (variable_get('firebase_cloud_messaging_project_id', '') == '') {
    $problems[] = t('You must set the project id to send a message.');
  }

  // private key path
  // - make sure it has been set
  // - make sure the file exists
  // - set its environment var
  $privateKeyPath = variable_get('firebase_cloud_messaging_private_key_path', '');
  if ($privateKeyPath == '') {
    $problems[] = t('You must set the path to your private key json file.');
  }
  else if (!file_exists($privateKeyPath)) {
    $problems[] = t("The file !file does not exist or cannot be accessed.", [
      '!file' => $privateKeyPath,
    ]);
  }
  else { putenv('GOOGLE_APPLICATION_CREDENTIALS=' . $privateKeyPath); }

  // If there were any problems, warn via watchdog or message.
  if (count($problems)) {
    foreach ($problems as $problem) {
      $watchdog ?
        watchdog('firebase', $problem, NULL, WATCHDOG_WARNING) :
        drupal_set_message($problem, 'warning');
    }
    return FALSE;
  }

  return TRUE;

}

function firebase_cloud_messaging_scopes() {

  // @see https://developers.google.com/identity/protocols/oauth2/scopes

  return [
    'https://www.googleapis.com/auth/firebase.messaging',
  ];

}

function firebase_cloud_messaging_bearer_token_cache_key() {
  return 'firebaseBearer';
}

function firebase_cloud_messaging_get_bearer_token($reset = FALSE) {
  module_load_include('inc', 'firebase', 'includes/http-v1');
  return _firebase_cloud_messaging_get_bearer_token($reset);
}
